CREATE TABLE PATIENT (
	pID INT NOT NULL,
    name VARCHAR(50) NOT NULL,
    birth_day DATE,
    phone INTEGER,
    address VARCHAR(100),
    disease VARCHAR(100) NOT NULL,
    treatment VARCHAR(100) NOT NULL,
    PRIMARY KEY (pID)
);

CREATE TABLE STAFF (
	sID INT NOT NULL,
    name VARCHAR(50) NOT NULL,
	birth_day DATE,
    phone INTEGER,
    PRIMARY KEY (sID)
);

CREATE TABLE DOCTOR (
	sID INT NOT NULL,
    name VARCHAR(50) NOT NULL,
	birth_day DATE,
    phone INTEGER,
    specialty VARCHAR(50),
    PRIMARY KEY (sID),
    FOREIGN KEY (sID) REFERENCES STAFF(sID)
);

CREATE TABLE NURSE (
	sID INT NOT NULL,
    name VARCHAR(50) NOT NULL,
	birth_day DATE,
    phone INTEGER,
    shift VARCHAR(10) NOT NULL CONSTRAINT shift_check CHECK (shift IN ('Morning', 'Evening', 'Night')),

    PRIMARY KEY (sID),
    FOREIGN KEY (sID) REFERENCES STAFF(sID)
);

CREATE TABLE WARD_BOY (
	sID INT NOT NULL,
    name VARCHAR(50) NOT NULL,
	birth_day DATE,
    phone INTEGER,
    duty VARCHAR(50),
    PRIMARY KEY (sID),
    FOREIGN KEY (sID) REFERENCES STAFF(sID)
);

CREATE TABLE ROOM (
	rID INT NOT NULL,
    is_available NUMBER(1) DEFAULT 1 NOT NULL CHECK (is_available IN (0, 1)),

    PRIMARY KEY (rID)
);

CREATE TABLE COMMON_ROOM(
	rID INT NOT NULL,
    new_attr VARCHAR(20),
	PRIMARY KEY (rID),
    FOREIGN KEY (rID) REFERENCES ROOM(rID)
);

CREATE TABLE OPERATION_THEATER(
	rID INT NOT NULL,
    new_attr VARCHAR(20),
	PRIMARY KEY (rID),
    FOREIGN KEY (rID) REFERENCES ROOM(rID)
);

CREATE TABLE ICU(
	rID INT NOT NULL,
    new_attr VARCHAR(20),
	PRIMARY KEY (rID),
    FOREIGN KEY (rID) REFERENCES ROOM(rID)
);

CREATE TABLE BILL (
-- FIXED BUT NEEDS RECHECKING
	bID INT,
    pID INT,
    duration INT NOT NULL,
    due_day DATE NOT NULL,
    price INT NOT NULL,
    PRIMARY KEY (bID),
    FOREIGN KEY (pID) REFERENCES PATIENT(pID)
);

-- RELATIONSHIPS -----------------------------------------------------------------
CREATE TABLE HANDLE (
	dID INT,
    pID INT,
    PRIMARY KEY (dID, pID)
    FOREIGN KEY (dID) REFERENCES DOCTOR(sID),
	FOREIGN KEY (pID) REFERENCES PATIENT(pID)
);

CREATE TABLE ADMITTED_TO (
	rID INT,
    pID INT,
    day_in DATE NOT NULL,
    day_out DATE NOT NULL,
    PRIMARY KEY (rID, pID),
	FOREIGN KEY (rID) REFERENCES ROOM(rID),
	FOREIGN KEY (pID) REFERENCES PATIENT(pID)
);

-- NEDD TO ADD MAINTAIN AND TAKE_CARE

CREATE TABLE MAINTAIN (
	rID INT UNIQUE NOT NULL,
    sID INT UNIQUE NOT NULL,
    PRIMARY KEY (rID, sID),
    FOREIGN KEY (rID) REFERENCES ROOM(rID),
    FOREIGN KEY (sID) REFERENCES STAFF(sID)
);

CREATE TABLE TAKE_CARE (
	pID INT UNIQUE NOT NULL,
    sID INT UNIQUE NOT NULL,
    PRIMARY KEY (pID, sID),
    FOREIGN KEY (pID) REFERENCES PATIENT(pID),
    FOREIGN KEY (sID) REFERENCES STAFF(sID)
);